### ISSUE TITLE
Newbie - How do you build?

### ISSUE THREAD

**Issue by orefalo** [themittenmac/TrueTree#6]
Hi,
At last a decent pstree project for osx

Newbie,
How do you build this?
Can you publish on brew?

**Comment by themittenmac** [comment]
Hi Oliver,

Are you looking to modify the source yourself before building? Because if
not you can just grab it from my website.

https://themittenmac.com/tools/

**Comment by orefalo** [comment]
Great thank you!
think you should add it to the main page ;-)
